<?php

namespace Database\Seeders;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $nessesary = [
            ['name' => 'استدراكي انجليزي'],
            ['name' => 'ثقافة اسلامية'],
            ['name' => 'اللغة العربية'],
            ['name' => 'اللغة الانجليزية 1'],
            ['name' => 'دراسات فلسطينية'],
            ['name' => 'مقدمة في الحاسوب'],
            ['name' => 'اللغة الانجليزية 2'],
        ];

        DB::table('nessesary_courses')->insert($nessesary);

        $nessesary_file = [
            ['name' => 'كتاب انجليزي 100', 'path' => 'https://drive.google.com/drive/folders/1dv1H9BaXia-9JQNwth3-2crbG182qnYs?usp=sharing'],
            ['name' => 'نماذج امتحانات', 'path' => 'https://drive.google.com/drive/folders/1tjcnrPFSOZt5JWvaDmSqWh3bZl4AiNlR?usp=sharing'],
            ['name' => 'كتاب ثقافة اسلامية', 'path' => 'https://drive.google.com/file/d/1xonMFYc1rwnXCsaL16GAdibxlkoGfWuf/view?usp=sharing'],
            ['name' => 'فيرست ثقافة اسلامية', 'path' => 'https://drive.google.com/drive/folders/1ts0qNLK7pixCqRpZX5M67HiT-WyfYD9v?usp=sharing'],
            ['name' => 'سكند ثقافة اسلامية', 'path' => 'https://drive.google.com/drive/folders/1-EdpZopBgfkP-GOEDobIaCCjFOfLBQEl?usp=sharing'],
            ['name' => 'فاينل ثقافة اسلامية', 'path' => 'https://drive.google.com/drive/folders/1oVREQ03nV1-h5sWOfKRRnYRiyNRS1lmw?usp=sharing'],
            ['name' => 'كتاب اللغة العربية', 'path' => 'https://drive.google.com/drive/folders/15sHdoKZRc5LYNLaUu6Ub15wzuWbb6yTU?usp=sharing'],
            ['name' => 'اسئلة سنوات', 'path' => 'https://drive.google.com/drive/folders/1QBPaQSK45F1RQ65ODkNHjJb38x_AsaLN?usp=sharing'],
            ['name' => 'تلاخيص لغة عربية', 'path' => 'https://drive.google.com/drive/folders/1Na-fekFkG8dX3B9f19a3ir3qwCu9vSqM?usp=sharing'],
            ['name' => 'كتاب انجليزي 101', 'path' => 'https://drive.google.com/drive/folders/1YaxhgDRM-aMwU23P2X3pZlpycuXEv440?usp=sharing'],
            ['name' => 'فيرست انجليزي 101', 'path' => 'https://drive.google.com/drive/folders/1Sq98BZiIyb6JwDFlti94R5S7R-MpvnEY?usp=sharing'],
            ['name' => 'سكند انجليزي 101', 'path' => 'https://drive.google.com/drive/folders/1-FIA47N8i0IronY87n_VAZ8joBiOCLHK?usp=sharing'],
            ['name' => 'فاينل انجليزي 101', 'path' => 'https://drive.google.com/drive/folders/1DXXVkNSAtFqHAI8_jhS4wIt6PJSSBr0S?usp=sharing'],
            ['name' => 'تلاخيص انجليزي 101', 'path' => 'https://drive.google.com/drive/folders/1uDjX9OqErQpm_KBpS-KsWOl2hw8vmTtS?usp=sharing'],
            ['name' => 'محاضرات د.وفاء', 'path' => 'https://onedrive.live.com/view.aspx?resid=DC985D1A6219922F!1496&ithint=file%2Cdocx&authkey=!ABMiDPG9V-GrGwg&fbclid=IwAR30S7YLtjHIVjil_u_8dKF0p_VlWgUsTQMq-Igv0RCSV1wBAs-rPJwu-UM'],
            ['name' => 'كتاب الدراسات الفلسطينية', 'path' => 'https://drive.google.com/drive/folders/16lpL3Xmm_rtR2387h8eHzakw04PtagV6?usp=sharing'],
            ['name' => 'امتحانات الدراسات الفلسطينية', 'path' => 'https://drive.google.com/drive/folders/1HC-NhuMHwB4hC_gvyZ5jMZz4X_zl8uCx?usp=sharing'],
            ['name' => 'تلخيص الكتاب', 'path' => 'https://drive.google.com/drive/folders/1HHtDPwIeY37qXgAqz_TXu8PyFg9YxhN0?usp=sharing'],
            ['name' => 'تقارير دراسات فلسطينية', 'path' => 'https://drive.google.com/drive/folders/1mV2lHhfj-_WfXm7Kg6NGfKsSlr9Z67N_?usp=sharing'],
            ['name' => 'سلايدات د.مي', 'path' => 'https://drive.google.com/drive/folders/1q8iMpTZK3sfwI7Qwd9J_YO-xeevgP1rN?usp=sharing'],
            ['name' => 'محاضرات د.مي', 'path' => 'https://www.youtube.com/playlist?list=PLg9wrIfTPI6Nf6LGxW_9mxdKriBnWwn2Y'],
            ['name' => 'كتاب انجليزي 102', 'path' => 'https://drive.google.com/drive/folders/1VbdZiGzn6lxXLXaOiyjv9YXVoEO9VoUj?usp=sharing'],
            ['name' => 'سلايدات انجليزي 102', 'path' => 'https://drive.google.com/drive/folders/1Qpo2cBRtf_WGmxr7yBsiBHy4FKih1zZP?usp=sharing'],
            ['name' => 'امتحانات وجاهية', 'path' => 'https://drive.google.com/drive/folders/1d0yCwj6L8pnr-SAkq05VasktstISlSXj?usp=sharing'],
            ['name' => 'امتحانات الكترونية', 'path' => 'https://drive.google.com/drive/folders/1Wvhd4fKjpdLJmFd0G63WvaBekXXWgYA4?usp=sharing'],
        ];
        DB::table('nessesary_files')->insert($nessesary_file);

        $nessesary_relation = [
            ['course_id' => '1', 'file_id' => '1'],
            ['course_id' => '1', 'file_id' => '2'],
            ['course_id' => '2', 'file_id' => '3'],
            ['course_id' => '2', 'file_id' => '4'],
            ['course_id' => '2', 'file_id' => '5'],
            ['course_id' => '2', 'file_id' => '6'],
            ['course_id' => '3', 'file_id' => '7'],
            ['course_id' => '3', 'file_id' => '8'],
            ['course_id' => '3', 'file_id' => '9'],
            ['course_id' => '4', 'file_id' => '10'],
            ['course_id' => '4', 'file_id' => '11'],
            ['course_id' => '4', 'file_id' => '12'],
            ['course_id' => '4', 'file_id' => '13'],
            ['course_id' => '4', 'file_id' => '14'],
            ['course_id' => '4', 'file_id' => '15'],
            ['course_id' => '5', 'file_id' => '16'],
            ['course_id' => '5', 'file_id' => '17'],
            ['course_id' => '5', 'file_id' => '18'],
            ['course_id' => '5', 'file_id' => '19'],
            ['course_id' => '6', 'file_id' => '20'],
            ['course_id' => '6', 'file_id' => '21'],
            ['course_id' => '7', 'file_id' => '22'],
            ['course_id' => '7', 'file_id' => '23'],
            ['course_id' => '7', 'file_id' => '24'],
            ['course_id' => '7', 'file_id' => '25'],
        ];

        DB::table('course_file_nessesaries')->insert($nessesary_relation);

        $collage = [
            ['name' => 'كلية الهندسة'],
            ['name' => 'كلية الطب'],
            ['name' => 'كلية العلوم'],
            ['name' => 'كلية الفنون'],
            ['name' => 'كلية القانون'],
            ['name' => 'كلية الاقتصاد'],
        ];
        DB::table('collages')->insert($collage);
        
        $users = [
            ['username' => 'jame3nta', 'password' => Hash::make('Boss2002'), 'collage_id' => '1', 'role' => 'admin'],
            ['username' => '12029591', 'password' => Hash::make('959leen120'), 'collage_id' => '6', 'role' => 'user'],
            ['username' => '12029178', 'password' => Hash::make('29453hala'), 'collage_id' => '6', 'role' => 'user'],
            ['username' => '12029453', 'password' => Hash::make('9453thara'), 'collage_id' => '1', 'role' => 'user'],
            ['username' => '12042556', 'password' => Hash::make('4255faten'), 'collage_id' => '2', 'role' => 'user'],
            ['username' => '12113105', 'password' => Hash::make('3105roaa'), 'collage_id' => '1', 'role' => 'user'],
            ['username' => '11819419', 'password' => Hash::make('1941abeer'), 'collage_id' => '1', 'role' => 'user'],
            ['username' => '12010996', 'password' => Hash::make('1099sima'), 'collage_id' => '1', 'role' => 'user'],
            ['username' => '12043235', 'password' => Hash::make('3235kinana'), 'collage_id' => '2', 'role' => 'user'],
            ['username' => '12027941', 'password' => Hash::make('2794islam'), 'collage_id' => '1', 'role' => 'user'],
            ['username' => '12028133', 'password' => Hash::make('2813siham'), 'collage_id' => '3', 'role' => 'user'],
            ['username' => '12027738', 'password' => Hash::make('7738dalia'), 'collage_id' => '4', 'role' => 'user'],
            ['username' => '12028453', 'password' => Hash::make('8953mosab'), 'collage_id' => '1', 'role' => 'user'],
            ['username' => 'adamakram', 'password' => Hash::make('8953adam'), 'collage_id' => '1', 'role' => 'user'],
            ['username' => '12029872', 'password' => Hash::make('9872maysam'), 'collage_id' => '3', 'role' => 'user'],
        ];
        DB::table('users')->insert($users);
        

        $major = [
            ['name' => 'أنظمة المعلومات الادارية' ,'collage_id' => '1'],
            ['name' => 'أنظمة المعلومات الحاسوبية' ,'collage_id' => '1'],
            ['name' => 'الشبكات وأمن المعلومات' ,'collage_id' => '1'],
            ['name' => 'الهندسة الصناعية' ,'collage_id' => '1'],
            ['name' => 'الهندسة الكهربائية' ,'collage_id' => '1'],
            ['name' => 'الهندسة الكيميائية' ,'collage_id' => '1'],
            ['name' => 'الهندسة المدنية' ,'collage_id' => '1'],
            ['name' => 'الهندسة المعمارية' ,'collage_id' => '1'],
            ['name' => 'الهندسة الميكانيكية' ,'collage_id' => '1'],
            ['name' => 'علم الحاسوب' ,'collage_id' => '1'],
            ['name' => 'علم الحاسوب في سوق العمل' ,'collage_id' => '1'],
            ['name' => 'هندسة الاتصالات' ,'collage_id' => '1'],
            ['name' => 'هندسة البناء' ,'collage_id' => '1'],
            ['name' => 'هندسة التخطيط وتكنولوجيا المدن' ,'collage_id' => '1'],
            ['name' => 'هندسة الجيومتكس' ,'collage_id' => '1'],
            ['name' => 'هندسة الحاسوب' ,'collage_id' => '1'],
            ['name' => 'هندسة الطاقة والبيئة' ,'collage_id' => '1'],
            ['name' => 'هندسة الميكاترونكس' ,'collage_id' => '1'],
            ['name' => 'هندسة علوم المواد' ,'collage_id' => '1'],
            ['name' => 'التخدير والانعاش التقني' ,'collage_id' => '2'],
            ['name' => 'صيدلة' ,'collage_id' => '2'],
            ['name' => 'دكتور صيدلي' ,'collage_id' => '2'],
            ['name' => 'تمريض' ,'collage_id' => '2'],
            ['name' => 'طب بشري' ,'collage_id' => '2'],
            ['name' => 'العلوم الطبية المخبرية' ,'collage_id' => '2'],
            ['name' => 'العلوم الطبية الحيوية' ,'collage_id' => '2'],
            ['name' => 'البصريات' ,'collage_id' => '2'],
            ['name' => 'القبالة' ,'collage_id' => '2'],
            ['name' => 'التصوير الطبي' ,'collage_id' => '2'],
            ['name' => 'علاج طبيعي' ,'collage_id' => '2'],
            ['name' => 'تكنولوجيا التروية القلبية' ,'collage_id' => '2'],
            ['name' => 'علم السمع والنطق' ,'collage_id' => '2'],
            ['name' => 'مستحضرات التجميل والعناية بالبشرة' ,'collage_id' => '2'],
            ['name' => 'الاحياء البيوتكنولوجيا' ,'collage_id' => '3'],
            ['name' => 'الرياضيات' ,'collage_id' => '3'],
            ['name' => 'العلوم الحياتية' ,'collage_id' => '3'],
            ['name' => 'الفيزياء' ,'collage_id' => '3'],
            ['name' => 'الكيمياء' ,'collage_id' => '3'],
            ['name' => 'الكيمياء التطبيقية' ,'collage_id' => '3'],
            ['name' => 'رئيسي رياضيات - فرعي تربية' ,'collage_id' => '3'],
            ['name' => 'رئيسي رياضيات - فرعي احصاء' ,'collage_id' => '3'],
            ['name' => 'رئيسي فيزياء - فرعي الكترونيات' ,'collage_id' => '3'],
            ['name' => 'رئيسي رياضيات - فرعي تأمين' ,'collage_id' => '3'],
            ['name' => 'رئيسي فيزياء - فرعي تربية' ,'collage_id' => '3'],
            ['name' => 'رئيسي كيمياء فرعي تربية' ,'collage_id' => '3'],
            ['name' => 'المحاسبة' ,'collage_id' => '6'],
            ['name' => 'ادارة الاعمال' ,'collage_id' => '6'],
            ['name' => 'ادارة اعمال - فرعي تأمين' ,'collage_id' => '6'],
            ['name' => 'اقتصاد - فرعي تأمين' ,'collage_id' => '6'],
            ['name' => 'الاذاعة والتلفزيون' ,'collage_id' => '6'],
            ['name' => 'الاتصال والاعلام الرقمي' ,'collage_id' => '6'],
            ['name' => 'الاقتصاد' ,'collage_id' => '6'],
            ['name' => 'التسويق - فرعي تأمين' ,'collage_id' => '6'],
            ['name' => 'الجغرافيا' ,'collage_id' => '6'],
            ['name' => 'العلاقات العامة والاتصال' ,'collage_id' => '6'],
            ['name' => 'العلوم السياسية' ,'collage_id' => '6'],
            ['name' => 'العلوم المالية والمصرفية' ,'collage_id' => '6'],
            ['name' => 'العلوم السياسية وادارة الدولة' ,'collage_id' => '5'],
            ['name' => 'القانون' ,'collage_id' => '5'],
            ['name' => 'رئيسي القانون - فرعي العلاقات الدولية' ,'collage_id' => '5'],
            ['name' => 'التصميم الداخلي' ,'collage_id' => '4'],
            ['name' => 'التصميم الجرافيكي' ,'collage_id' => '4'],
            ['name' => 'الرسم والتصوير' ,'collage_id' => '4'],
            ['name' => ' الموسيقى' ,'collage_id' => '4'],
            ['name' => 'تصميم الالعاب' ,'collage_id' => '4'],
            ['name' => 'فن الخزف' ,'collage_id' => '4'],
        ];
        DB::table('majors')->insert($major);

        $cousre = [
            ['name' => 'كالك 1','collage_id' => '1'],
            ['name' => 'كالك 2','collage_id' => '1'],
            ['name' => 'كالك 3','collage_id' => '1'],
            ['name' => 'فيزياء عامة  1','collage_id' => '1'],
            ['name' => 'فيزياء عامة 2','collage_id' => '1'],
            ['name' => 'مختبر فيزياء عامة للهندسة','collage_id' => '1'],
            ['name' => 'كيمياء عامة  1','collage_id' => '1'],
            ['name' => 'مختبر كيمياء عامة  1','collage_id' => '1'],
            ['name' => 'كيمياء عامة  2','collage_id' => '1'],
            ['name' => 'مختبر كيمياء عامة  2','collage_id' => '1'],
            ['name' => 'مقدمة انظمة معلومات ادارية','collage_id' => '1'],
            ['name' => 'احصاء واحتمالات','collage_id' => '1'],
            ['name' => 'مبادئ محاسبية','collage_id' => '1'],
            ['name' => 'امن المعلومات واخلاقياتها','collage_id' => '1'],
            ['name' => 'تركيب البيانات','collage_id' => '1'],
            ['name' => 'كتابة تقارير فنية','collage_id' => '1'],
            ['name' => 'وايرليس','collage_id' => '1'],
            ['name' => 'اساسيات البرمجة الكينونية','collage_id' => '1'],
            ['name' => 'ديسكريت','collage_id' => '1'],
            ['name' => 'اسمبلي','collage_id' => '1'],
            ['name' => 'رسم هندسي','collage_id' => '1'],
            ['name' => 'برمجة حاسوب','collage_id' => '1'],
            ['name' => 'رياضيات هندسية','collage_id' => '1'],
            ['name' => 'نيوماريكال','collage_id' => '1'],
            ['name' => 'ميكانيكا هندسية','collage_id' => '1'],
            ['name' => 'ميكانيكا الموائع','collage_id' => '1'],
            ['name' => 'ديناميكا حرارية','collage_id' => '1'],
            ['name' => 'مبادئ الحسابات الكيميائية','collage_id' => '1'],
            ['name' => 'مبادئ اتصالات','collage_id' => '1'],
            ['name' => 'ديجتال','collage_id' => '1'],
            ['name' => 'ديجتال 1','collage_id' => '1'],
            ['name' => 'مختبر ديجتال 1','collage_id' => '1'],
            ['name' => 'ديجيتال 2','collage_id' => '1'],
            ['name' => 'مختبر ديجتال 2','collage_id' => '1'],
            ['name' => 'ديجيتال 3','collage_id' => '1'],
            ['name' => 'مختبر ديجتال 3','collage_id' => '1'],
            ['name' => 'كهرو 1','collage_id' => '1'],
            ['name' => 'كهرو 2','collage_id' => '1'],
            ['name' => 'كونترول','collage_id' => '1'],
            ['name' => 'مختبر كونترول','collage_id' => '1'],
            ['name' => 'الكترونية 1','collage_id' => '1'],
            ['name' => 'مختبر الكترونية','collage_id' => '1'],
            ['name' => 'الكترونية 2','collage_id' => '1'],
            ['name' => 'سينسور','collage_id' => '1'],
            ['name' => 'بارشال','collage_id' => '1'],
            ['name' => 'بور 1','collage_id' => '1'],
            ['name' => 'بور 2','collage_id' => '1'],
            ['name' => 'مشين','collage_id' => '1'],
            ['name' => 'سيركت 1','collage_id' => '1'],
            ['name' => 'مختبر سيركت 1','collage_id' => '1'],
            ['name' => 'سيركت 2','collage_id' => '1'],
            ['name' => 'مبادئ برمجة 1','collage_id' => '1'],
            ['name' => 'مبادئ برمجة 2','collage_id' => '1'],
            ['name' => 'داتا ستركتشر-علم','collage_id' => '1'],
            ['name' => 'داتا بيس-علم','collage_id' => '1'],
            ['name' => 'الجوريثم-علم','collage_id' => '1'],
            ['name' => 'لينير','collage_id' => '1'],
            ['name' => 'ويب 1','collage_id' => '1'],
            ['name' => 'تشفير وامن معلومات','collage_id' => '1'],
            ['name' => 'ذكاء الي','collage_id' => '1'],
            ['name' => 'سوفتوير-علم', 'collage_id' => '1'],
            ['name' => 'ثيوري','collage_id' => '1'],
            ['name' => 'شبكات-علم','collage_id' => '1'],
            ['name' => 'اساسيات ذكاء اصطناعي','collage_id' => '1'],
            ['name' => 'نظرية الاحتمالات','collage_id' => '1'],
            ['name' => 'شبكات 1','collage_id' => '1'],
            ['name' => 'شبكات 2','collage_id' => '1'],
            ['name' => 'مختبر شبكات','collage_id' => '1'],
            ['name' => 'سيجنال','collage_id' => '1'],
            ['name' => 'هوائيات','collage_id' => '1'],
            ['name' => 'نظرية المعلومات والترميز','collage_id' => '1'],
            ['name' => 'معالجة الكلام والصوت','collage_id' => '1'],
            ['name' => 'انظمة الاتصالات النقالة','collage_id' => '1'],
            ['name' => 'اتصالات الالياف الضوئية','collage_id' => '1'],
            ['name' => 'داتا ستركتشر','collage_id' => '1'],
            ['name' => 'مايكروبروسيسور','collage_id' => '1'],
            ['name' => 'مختبر مايكروبروسيسور','collage_id' => '1'],
            ['name' => 'جافا','collage_id' => '1'],
            ['name' => 'داتا بيس','collage_id' => '1'],
            ['name' => 'الجوريثم','collage_id' => '1'],
            ['name' => 'اتصالات','collage_id' => '1'],
            ['name' => 'عمارة حاسوب 1','collage_id' => '1'],
            ['name' => 'عمارة حاسوب 2','collage_id' => '1'],
            ['name' => 'ايميج','collage_id' => '1'],
            ['name' => 'سوفتوير','collage_id' => '1'],
            ['name' => 'ويب','collage_id' => '1'],
            ['name' => 'نظم التشغيل','collage_id' => '1'],
            ['name' => 'الذكاء الاصطناعي','collage_id' => '1'],
            ['name' => 'مختبر cpu','collage_id' => '1'],
            ['name' => 'نظرية الالات','collage_id' => '1'],
            ['name' => 'مقدمة في الادارة الهندسية','collage_id' => '1'],
            ['name' => 'مقاومة المواد','collage_id' => '1'],
            ['name' => 'مشاغل هندسة 1','collage_id' => '1'],
            ['name' => 'ستاتيكا','collage_id' => '1'],
            ['name' => 'روبوتات','collage_id' => '1'],
            ['name' => 'الات كهربائية','collage_id' => '1'],
            ['name' => 'احصاء واحتمالات للمهندسين','collage_id' => '1'],
            ['name' => 'مبادئ نظم المعلومات الجغرافية','collage_id' => '1'],
            ['name' => 'مبادئ التصميم','collage_id' => '1'],
            ['name' => 'مبادئ التخطيط','collage_id' => '1'],
            ['name' => 'الاقتصاد للمهندسين','collage_id' => '1'],
            ['name' => 'مدخل الى تصاميم البيئة','collage_id' => '1'],
            ['name' => 'تقنيات الرسم والاظهار','collage_id' => '1'],
            // كلية الطب
            ['name' => 'مصطلحات طبية','collage_id' => '2'],
            ['name' => 'كمياء تخدير','collage_id' => '2'],
            ['name' => 'فيزياء تخدير','collage_id' => '2'],
            ['name' => 'فارما','collage_id' => '2'],
            ['name' => 'طب بديل','collage_id' => '2'],
            ['name' => 'تغذية طبية','collage_id' => '2'],
            ['name' => 'اناتومي 1','collage_id' => '2'],
            ['name' => 'اناتومي 2','collage_id' => '2'],
            ['name' => 'احصاء حيوي','collage_id' => '2'],
            ['name' => 'اسعافات اولية','collage_id' => '2'],
            ['name' => 'اساسيات تخدير','collage_id' => '2'],
            ['name' => 'اخلاقيات طبية','collage_id' => '2'],
            ['name' => 'احياء عامة','collage_id' => '2'],
            ['name' => 'الصحة العامة','collage_id' => '2'],
            ['name' => 'مقدمة التشريح','collage_id' => '2'],
            ['name' => 'كيمياء عامة - طب','collage_id' => '2'],
            ['name' => 'مختبر كيمياء عامة - طب','collage_id' => '2'],
            ['name' => 'صيدلة فيزيائية 2','collage_id' => '2'],
            ['name' => 'مختبر صيدلة فيزياء','collage_id' => '2'],
            ['name' => 'علم الادوية 1','collage_id' => '2'],
            ['name' => 'كيمياء عضوية','collage_id' => '2'],
            ['name' => 'مختبر كيمياء عضوية','collage_id' => '2'],
            ['name' => 'كيمياء تحليلية','collage_id' => '2'],
            ['name' => 'مختبر كيمياء تحليلية','collage_id' => '2'],
            ['name' => 'اخلاقيات مهنة الصيدلة','collage_id' => '2'],
            ['name' => 'تغذية طبية','collage_id' => '2'],
            ['name' => 'فيزياء حيوية','collage_id' => '2'],
            ['name' => 'مبادئ كيمياء حيوية','collage_id' => '2'],
            ['name' => 'علم الاحياء الدقيقة','collage_id' => '2'],
            ['name' => 'مختبر علم الاحياء الدقيقة','collage_id' => '2'],
            ['name' => 'فسيو 1','collage_id' => '2'],
            ['name' => 'ثوراكس نظري','collage_id' => '2'],
            ['name' => 'ثوراكس عملي','collage_id' => '2'],
            ['name' => 'صيدلية فيزيائية','collage_id' => '2'],
            ['name' => 'سايكلوجي','collage_id' => '2'],
            ['name' => 'باثولوجي','collage_id' => '2'],
            ['name' => 'ريسيرتش','collage_id' => '2'],
            ['name' => 'علم السلوك الطبي','collage_id' => '2'],
            ['name' => 'صحة الامومة التمريضية','collage_id' => '2'],
            ['name' => 'التقييم الصحي','collage_id' => '2'],
            ['name' => 'مختبر التقييم الصحي','collage_id' => '2'],
            ['name' => 'علم النمو والتطوير','collage_id' => '2'],
            ['name' => 'موليك','collage_id' => '2'],
            ['name' => 'هيدونيك','collage_id' => '2'],
            ['name' => 'مايكرو','collage_id' => '2'],
            ['name' => 'فسيو 2','collage_id' => '2'],
            ['name' => 'سلوك','collage_id' => '2'],
            ['name' => 'ببلك','collage_id' => '2'],
            ['name' => 'جنتكس','collage_id' => '2'],
            ['name' => 'ابر ولور','collage_id' => '2'],
            ['name' => 'سايكو','collage_id' => '2'],
            ['name' => 'هيماتولوجي','collage_id' => '2'],
            ['name' => 'هيستولوجي 2','collage_id' => '2'],
            ['name' => 'باقو 1','collage_id' => '2'],
            ['name' => 'باثو 2','collage_id' => '2'],
            ['name' => 'فارما 2','collage_id' => '2'],
            ['name' => 'نيورو','collage_id' => '2'],
            ['name' => 'هندسة وفيزياء البصريات','collage_id' => '2'],
            ['name' => 'علم تشريح وفسيولوجيا العين','collage_id' => '2'],
            ['name' => 'بصريات الرؤية الفسيولوجية','collage_id' => '2'],
            ['name' => 'العناية البصرية الاولية','collage_id' => '2'],
            ['name' => 'التقنيات التشخيصية 1','collage_id' => '2'],
            ['name' => 'الادراك البصري','collage_id' => '2'],
            ['name' => 'مقدمة في القبالة','collage_id' => '2'],
            ['name' => 'علم قبالة 1','collage_id' => '2'],
            ['name' => 'اخلاقيات مهنة القبالة','collage_id' => '2'],
            ['name' => 'علم النمو والتطور','collage_id' => '2'],
            ['name' => 'مقدمة في العلاج الطبيعي','collage_id' => '2'],
            ['name' => 'علم النفس للتأهيل','collage_id' => '2'],
            ['name' => 'تشريح عضلي هيكلي - نظري','collage_id' => '2'],
            ['name' => 'تشريح عضلي هيكلي - عملي','collage_id' => '2'],
            ['name' => 'تحليل المشي والقوام','collage_id' => '2'],
            ['name' => 'طرق العلاج الطبيعي','collage_id' => '2'],
            ['name' => 'تقييم عضلي هيكلي','collage_id' => '2'],
            ['name' => 'علم وظائف التمرين','collage_id' => '2'],
            ['name' => 'علم الاعصاب','collage_id' => '2'],
            ['name' => 'اورثو','collage_id' => '2'],
            ['name' => 'تمارين علاجية','collage_id' => '2'],
            ['name' => 'لغويات عامة','collage_id' => '2'],
            ['name' => 'مدخل للتربية الخاصة','collage_id' => '2'],
            ['name' => 'علم الصوت الفيزيائي','collage_id' => '2'],
            ['name' => 'صوتيات','collage_id' => '2'],
            ['name' => 'تطور الطفل','collage_id' => '2'],
            ['name' => 'اناتومي نطق','collage_id' => '2'],
            ['name' => 'اناتومي سمع','collage_id' => '2'],
            ['name' => 'اكتساب اللغة وتطويرها','collage_id' => '2'],
            ['name' => 'امراض النطق الطبية','collage_id' => '2'],
            // كلية العلوم
            ['name' => 'فيزياء رياضية 1','collage_id' => '3'],
            ['name' => 'فيزياء موجية وضوء','collage_id' => '3'],
            ['name' => 'الكترونيات','collage_id' => '3'],
            ['name' => 'مختبر الكترونيات 1','collage_id' => '3'],
            ['name' => 'فيزياء حديثة 1','collage_id' => '3'],
            ['name' => 'فيزياء حديثة 2','collage_id' => '3'],
            ['name' => 'الريادة والابداع','collage_id' => '3'],
            ['name' => 'الحاسوب في الفيزياء','collage_id' => '3'],
            ['name' => 'كوانتم 1','collage_id' => '3'],
            ['name' => 'موضوعات خاصة','collage_id' => '3'],
            ['name' => 'EM1','collage_id' => '3'],
            ['name' => 'EM2','collage_id' => '3'],
            ['name' => 'ثيروداينمك','collage_id' => '3'],
            ['name' => 'فيزياء رياضية 2','collage_id' => '3'],
            ['name' => 'كلاسيكية 1','collage_id' => '3'],
            ['name' => 'فيزياء عملي 1','collage_id' => '3'],
            //كلية الاقتصاد
            ['name' => 'محاسبة 1','collage_id' => '6'],
            ['name' => 'محاسبة 2','collage_id' => '6'],
            ['name' => 'ادارة 1','collage_id' => '6'],
            ['name' => 'محاسبة متوسطة 1','collage_id' => '6'],
            ['name' => 'محاسبة شركات','collage_id' => '6'],
            ['name' => 'مالية 1','collage_id' => '6'],
            ['name' => 'اسواق مالية','collage_id' => '6'],
            ['name' => 'تمويل','collage_id' => '6'],
            ['name' => 'تسويق','collage_id' => '6'],
            ['name' => 'اقتصاد جزئي','collage_id' => '6'],
            ['name' => 'محاسبة حكومية','collage_id' => '6'],
            //كلية الفنون
            ['name' => 'مدخل الى الموسيقى','collage_id' => '4'],
            ['name' => 'تظريات التصميم ومناهجه','collage_id' => '4'],
            ['name' => 'مدخل الى الفنون','collage_id' => '4'],
            ['name' => 'تاريخ وتذوق الفن','collage_id' => '4'],
        ];
        DB::table('courses')->insert($cousre);

        $relation = [
            // انظمة المعلومات الادارية
            ['major_id' => '1', 'course_id' => '11'],
            ['major_id' => '1', 'course_id' => '12'],
            ['major_id' => '1', 'course_id' => '13'],
            // امن معلومات وشبكات
            ['major_id' => '3', 'course_id' => '19'],
            ['major_id' => '3', 'course_id' => '4'],
            ['major_id' => '3', 'course_id' => '20'],
            ['major_id' => '3', 'course_id' => '14'],
            ['major_id' => '3', 'course_id' => '15'],
            ['major_id' => '3', 'course_id' => '18'],
            ['major_id' => '3', 'course_id' => '16'],
            ['major_id' => '3', 'course_id' => '17'],
            // الهندسة الصناعية
            ['major_id' => '4', 'course_id' => '1'],
            ['major_id' => '4', 'course_id' => '2'],
            ['major_id' => '4', 'course_id' => '3'],
            ['major_id' => '4', 'course_id' => '4'],
            ['major_id' => '4', 'course_id' => '5'],
            ['major_id' => '4', 'course_id' => '6'],
            ['major_id' => '4', 'course_id' => '7'],
            ['major_id' => '4', 'course_id' => '8'],
            ['major_id' => '4', 'course_id' => '21'],
            ['major_id' => '4', 'course_id' => '22'],
            ['major_id' => '4', 'course_id' => '23'],
            ['major_id' => '4', 'course_id' => '24'],
            // الهندسة الكهربائية
            ['major_id' => '5', 'course_id' => '1'],
            ['major_id' => '5', 'course_id' => '2'],
            ['major_id' => '5', 'course_id' => '3'],
            ['major_id' => '5', 'course_id' => '4'],
            ['major_id' => '5', 'course_id' => '5'],
            ['major_id' => '5', 'course_id' => '6'],
            ['major_id' => '5', 'course_id' => '7'],
            ['major_id' => '5', 'course_id' => '8'],
            ['major_id' => '5', 'course_id' => '21'],
            ['major_id' => '5', 'course_id' => '22'],
            ['major_id' => '5', 'course_id' => '23'],
            ['major_id' => '5', 'course_id' => '24'],
            ['major_id' => '5', 'course_id' => '25'],
            ['major_id' => '5', 'course_id' => '29'],
            ['major_id' => '5', 'course_id' => '30'],
            ['major_id' => '5', 'course_id' => '36'],
            ['major_id' => '5', 'course_id' => '37'],
            ['major_id' => '5', 'course_id' => '38'],
            ['major_id' => '5', 'course_id' => '39'],
            ['major_id' => '5', 'course_id' => '40'],
            ['major_id' => '5', 'course_id' => '41'],
            ['major_id' => '5', 'course_id' => '42'],
            ['major_id' => '5', 'course_id' => '44'],
            ['major_id' => '5', 'course_id' => '45'],
            ['major_id' => '5', 'course_id' => '46'],
            ['major_id' => '5', 'course_id' => '47'],
            ['major_id' => '5', 'course_id' => '48'],
            ['major_id' => '5', 'course_id' => '49'],
            ['major_id' => '5', 'course_id' => '50'],
            ['major_id' => '5', 'course_id' => '51'],
            // الهندسة الكيميائية 
            ['major_id' => '6', 'course_id' => '1'],
            ['major_id' => '6', 'course_id' => '2'],
            ['major_id' => '6', 'course_id' => '3'],
            ['major_id' => '6', 'course_id' => '4'],
            ['major_id' => '6', 'course_id' => '5'],
            ['major_id' => '6', 'course_id' => '6'],
            ['major_id' => '6', 'course_id' => '7'],
            ['major_id' => '6', 'course_id' => '8'],
            ['major_id' => '6', 'course_id' => '9'],
            ['major_id' => '6', 'course_id' => '10'],
            ['major_id' => '6', 'course_id' => '21'],
            ['major_id' => '6', 'course_id' => '22'],
            ['major_id' => '6', 'course_id' => '23'],
            ['major_id' => '6', 'course_id' => '24'],
            ['major_id' => '6', 'course_id' => '25'],
            ['major_id' => '6', 'course_id' => '26'],
            ['major_id' => '6', 'course_id' => '27'],
            ['major_id' => '6', 'course_id' => '28'],
            // الهندسة المدنية
            ['major_id' => '7', 'course_id' => '1'],
            ['major_id' => '7', 'course_id' => '2'],
            ['major_id' => '7', 'course_id' => '3'],
            ['major_id' => '7', 'course_id' => '4'],
            ['major_id' => '7', 'course_id' => '5'],
            ['major_id' => '7', 'course_id' => '6'],
            ['major_id' => '7', 'course_id' => '7'],
            ['major_id' => '7', 'course_id' => '8'],
            ['major_id' => '7', 'course_id' => '21'],
            ['major_id' => '7', 'course_id' => '22'],
            ['major_id' => '7', 'course_id' => '23'],
            // الهندسة المعمارية
            ['major_id' => '8', 'course_id' => '1'],
            ['major_id' => '8', 'course_id' => '2'],
            ['major_id' => '8', 'course_id' => '4'],
            ['major_id' => '8', 'course_id' => '5'],
            ['major_id' => '8', 'course_id' => '6'],
            //الهندسة المكانيكية
            ['major_id' => '9', 'course_id' => '1'],
            ['major_id' => '9', 'course_id' => '2'],
            ['major_id' => '9', 'course_id' => '3'],
            ['major_id' => '9', 'course_id' => '4'],
            ['major_id' => '9', 'course_id' => '5'],
            ['major_id' => '9', 'course_id' => '6'],
            ['major_id' => '9', 'course_id' => '7'],
            ['major_id' => '9', 'course_id' => '8'],
            ['major_id' => '9', 'course_id' => '21'],
            ['major_id' => '9', 'course_id' => '22'],
            ['major_id' => '9', 'course_id' => '23'],
            // علم الحاسوب
            ['major_id' => '10', 'course_id' => '1'],
            ['major_id' => '10', 'course_id' => '2'],
            ['major_id' => '10', 'course_id' => '4'],
            ['major_id' => '10', 'course_id' => '5'],
            ['major_id' => '10', 'course_id' => '7'],
            ['major_id' => '10', 'course_id' => '8'],
            ['major_id' => '10', 'course_id' => '9'],
            ['major_id' => '10', 'course_id' => '52'],
            ['major_id' => '10', 'course_id' => '53'],
            ['major_id' => '10', 'course_id' => '54'],
            ['major_id' => '10', 'course_id' => '55'],
            ['major_id' => '10', 'course_id' => '56'],
            ['major_id' => '10', 'course_id' => '57'],
            ['major_id' => '10', 'course_id' => '58'],
            ['major_id' => '10', 'course_id' => '48'],
            ['major_id' => '10', 'course_id' => '30'],
            ['major_id' => '10', 'course_id' => '19'],
            ['major_id' => '10', 'course_id' => '59'],
            ['major_id' => '10', 'course_id' => '60'],
            ['major_id' => '10', 'course_id' => '24'],
            // علم حاسوب في سوق العمل
            ['major_id' => '11', 'course_id' => '1'],
            ['major_id' => '11', 'course_id' => '2'],
            ['major_id' => '11', 'course_id' => '4'],
            ['major_id' => '11', 'course_id' => '5'],
            ['major_id' => '11', 'course_id' => '6'],
            ['major_id' => '11', 'course_id' => '22'],
            ['major_id' => '11', 'course_id' => '52'],
            ['major_id' => '11', 'course_id' => '53'],
            ['major_id' => '11', 'course_id' => '63'],
            ['major_id' => '11', 'course_id' => '19'],
            ['major_id' => '11', 'course_id' => '55'],
            ['major_id' => '11', 'course_id' => '56'],
            ['major_id' => '11', 'course_id' => '61'],
            ['major_id' => '11', 'course_id' => '62'],
            ['major_id' => '11', 'course_id' => '65'],
            ['major_id' => '11', 'course_id' => '64'],
            // هندسة الاتصالات
            ['major_id' => '12', 'course_id' => '1'],
            ['major_id' => '12', 'course_id' => '2'],
            ['major_id' => '12', 'course_id' => '3'],
            ['major_id' => '12', 'course_id' => '4'],
            ['major_id' => '12', 'course_id' => '5'],
            ['major_id' => '12', 'course_id' => '6'],
            ['major_id' => '12', 'course_id' => '7'],
            ['major_id' => '12', 'course_id' => '8'],
            ['major_id' => '12', 'course_id' => '21'],
            ['major_id' => '12', 'course_id' => '22'],
            ['major_id' => '12', 'course_id' => '23'],
            ['major_id' => '12', 'course_id' => '24'],
            ['major_id' => '12', 'course_id' => '32'],
            ['major_id' => '12', 'course_id' => '49'],
            ['major_id' => '12', 'course_id' => '50'],
            ['major_id' => '12', 'course_id' => '51'],
            ['major_id' => '12', 'course_id' => '41'],
            ['major_id' => '12', 'course_id' => '42'],
            ['major_id' => '12', 'course_id' => '43'],
            ['major_id' => '12', 'course_id' => '29'],
            ['major_id' => '12', 'course_id' => '69'],
            ['major_id' => '12', 'course_id' => '19'],
            ['major_id' => '12', 'course_id' => '70'],
            ['major_id' => '12', 'course_id' => '71'],
            ['major_id' => '12', 'course_id' => '72'],
            ['major_id' => '12', 'course_id' => '73'],
            ['major_id' => '12', 'course_id' => '74'],
            ['major_id' => '12', 'course_id' => '66'],
            //هندسة البناء
            ['major_id' => '13', 'course_id' => '1'],
            ['major_id' => '13', 'course_id' => '2'],
            ['major_id' => '13', 'course_id' => '3'],
            ['major_id' => '13', 'course_id' => '4'],
            ['major_id' => '13', 'course_id' => '5'],
            ['major_id' => '13', 'course_id' => '6'],
            ['major_id' => '13', 'course_id' => '7'],
            ['major_id' => '13', 'course_id' => '8'],
            ['major_id' => '13', 'course_id' => '21'],
            ['major_id' => '13', 'course_id' => '22'],
            ['major_id' => '13', 'course_id' => '23'],
            // هندسة التخطيط 
            ['major_id' => '14', 'course_id' => '1'],
            ['major_id' => '14', 'course_id' => '2'],
            ['major_id' => '14', 'course_id' => '4'],
            ['major_id' => '14', 'course_id' => '21'],
            ['major_id' => '14', 'course_id' => '97'],
            ['major_id' => '14', 'course_id' => '98'],
            ['major_id' => '14', 'course_id' => '99'],
            ['major_id' => '14', 'course_id' => '100'],
            ['major_id' => '14', 'course_id' => '101'],
            ['major_id' => '14', 'course_id' => '102'],
            ['major_id' => '14', 'course_id' => '103'],
            // هندسة الحاسوب
            ['major_id' => '16', 'course_id' => '1'],
            ['major_id' => '16', 'course_id' => '2'],
            ['major_id' => '16', 'course_id' => '3'],
            ['major_id' => '16', 'course_id' => '4'],
            ['major_id' => '16', 'course_id' => '5'],
            ['major_id' => '16', 'course_id' => '6'],
            ['major_id' => '16', 'course_id' => '7'],
            ['major_id' => '16', 'course_id' => '8'],
            ['major_id' => '16', 'course_id' => '21'],
            ['major_id' => '16', 'course_id' => '22'],
            ['major_id' => '16', 'course_id' => '23'],
            ['major_id' => '16', 'course_id' => '24'],
            ['major_id' => '16', 'course_id' => '31'],
            ['major_id' => '16', 'course_id' => '32'],
            ['major_id' => '16', 'course_id' => '33'],
            ['major_id' => '16', 'course_id' => '34'],
            ['major_id' => '16', 'course_id' => '35'],
            ['major_id' => '16', 'course_id' => '36'],
            ['major_id' => '16', 'course_id' => '41'],
            ['major_id' => '16', 'course_id' => '42'],
            ['major_id' => '16', 'course_id' => '43'],
            ['major_id' => '16', 'course_id' => '49'],
            ['major_id' => '16', 'course_id' => '50'],
            ['major_id' => '16', 'course_id' => '66'],
            ['major_id' => '16', 'course_id' => '67'],
            ['major_id' => '16', 'course_id' => '68'],
            ['major_id' => '16', 'course_id' => '69'],
            ['major_id' => '16', 'course_id' => '75'],
            ['major_id' => '16', 'course_id' => '76'],
            ['major_id' => '16', 'course_id' => '77'],
            ['major_id' => '16', 'course_id' => '78'],
            ['major_id' => '16', 'course_id' => '79'],
            ['major_id' => '16', 'course_id' => '80'],
            ['major_id' => '16', 'course_id' => '81'],
            ['major_id' => '16', 'course_id' => '82'],
            ['major_id' => '16', 'course_id' => '83'],
            ['major_id' => '16', 'course_id' => '84'],
            ['major_id' => '16', 'course_id' => '85'],
            ['major_id' => '16', 'course_id' => '86'],
            ['major_id' => '16', 'course_id' => '87'],
            ['major_id' => '16', 'course_id' => '88'],
            ['major_id' => '16', 'course_id' => '89'],
            ['major_id' => '16', 'course_id' => '97'],
            // هندسة الطاقة والببئية
            ['major_id' => '17', 'course_id' => '1'],
            ['major_id' => '17', 'course_id' => '2'],
            ['major_id' => '17', 'course_id' => '3'],
            ['major_id' => '17', 'course_id' => '4'],
            ['major_id' => '17', 'course_id' => '5'],
            ['major_id' => '17', 'course_id' => '6'],
            ['major_id' => '17', 'course_id' => '7'],
            ['major_id' => '17', 'course_id' => '8'],
            ['major_id' => '17', 'course_id' => '21'],
            ['major_id' => '17', 'course_id' => '22'],
            ['major_id' => '17', 'course_id' => '23'],
            // هندسة الميكاترونكس
            ['major_id' => '18', 'course_id' => '1'],
            ['major_id' => '18', 'course_id' => '2'],
            ['major_id' => '18', 'course_id' => '3'],
            ['major_id' => '18', 'course_id' => '4'],
            ['major_id' => '18', 'course_id' => '5'],
            ['major_id' => '18', 'course_id' => '6'],
            ['major_id' => '18', 'course_id' => '7'],
            ['major_id' => '18', 'course_id' => '8'],
            ['major_id' => '18', 'course_id' => '21'],
            ['major_id' => '18', 'course_id' => '22'],
            ['major_id' => '18', 'course_id' => '23'],
            ['major_id' => '18', 'course_id' => '90'],
            ['major_id' => '18', 'course_id' => '91'],
            ['major_id' => '18', 'course_id' => '92'],
            ['major_id' => '18', 'course_id' => '93'],
            ['major_id' => '18', 'course_id' => '94'],
            // التخدير والانعاش التقني
            ['major_id' => '20', 'course_id' => '104'],
            ['major_id' => '20', 'course_id' => '105'],
            ['major_id' => '20', 'course_id' => '106'],
            ['major_id' => '20', 'course_id' => '107'],
            ['major_id' => '20', 'course_id' => '108'],
            ['major_id' => '20', 'course_id' => '109'],
            ['major_id' => '20', 'course_id' => '110'],
            ['major_id' => '20', 'course_id' => '111'],
            ['major_id' => '20', 'course_id' => '112'],
            ['major_id' => '20', 'course_id' => '113'],
            ['major_id' => '20', 'course_id' => '114'],
            ['major_id' => '20', 'course_id' => '115'],
            ['major_id' => '20', 'course_id' => '116'],
            // صيدلة
            ['major_id' => '21', 'course_id' => '117'],
            ['major_id' => '21', 'course_id' => '118'],
            ['major_id' => '21', 'course_id' => '119'],
            ['major_id' => '21', 'course_id' => '120'],
            ['major_id' => '21', 'course_id' => '121'],
            ['major_id' => '21', 'course_id' => '122'],
            ['major_id' => '21', 'course_id' => '123'],
            ['major_id' => '21', 'course_id' => '124'],
            ['major_id' => '21', 'course_id' => '127'],
            ['major_id' => '21', 'course_id' => '128'],
            ['major_id' => '21', 'course_id' => '129'],
            ['major_id' => '21', 'course_id' => '130'],
            ['major_id' => '21', 'course_id' => '131'],
            ['major_id' => '21', 'course_id' => '132'],
            ['major_id' => '21', 'course_id' => '133'],
            ['major_id' => '21', 'course_id' => '113'],
            // دكتور صيدلي
            ['major_id' => '22', 'course_id' => '118'],
            ['major_id' => '22', 'course_id' => '124'],
            ['major_id' => '22', 'course_id' => '125'],
            ['major_id' => '22', 'course_id' => '119'],
            ['major_id' => '22', 'course_id' => '120'],
            ['major_id' => '22', 'course_id' => '126'],
            ['major_id' => '22', 'course_id' => '127'],
            ['major_id' => '22', 'course_id' => '132'],
            ['major_id' => '22', 'course_id' => '133'],
            ['major_id' => '22', 'course_id' => '113'],
            ['major_id' => '22', 'course_id' => '112'],
            ['major_id' => '22', 'course_id' => '128'],
            ['major_id' => '22', 'course_id' => '116'],
            ['major_id' => '22', 'course_id' => '129'],
            ['major_id' => '22', 'course_id' => '130'],
            ['major_id' => '22', 'course_id' => '131'],
            ['major_id' => '22', 'course_id' => '134'],
            ['major_id' => '22', 'course_id' => '135'],
            ['major_id' => '22', 'course_id' => '136'],
            ['major_id' => '22', 'course_id' => '137'],
            ['major_id' => '22', 'course_id' => '138'],
            ['major_id' => '22', 'course_id' => '139'],
            ['major_id' => '22', 'course_id' => '107'],
            // تمريض
            ['major_id' => '23', 'course_id' => '117'],
            ['major_id' => '23', 'course_id' => '121'],
            ['major_id' => '23', 'course_id' => '122'],
            ['major_id' => '23', 'course_id' => '123'],
            ['major_id' => '23', 'course_id' => '124'],
            ['major_id' => '23', 'course_id' => '125'],
            ['major_id' => '23', 'course_id' => '126'],
            ['major_id' => '23', 'course_id' => '127'],
            ['major_id' => '23', 'course_id' => '140'],
            ['major_id' => '23', 'course_id' => '141'],
            ['major_id' => '23', 'course_id' => '142'],
            ['major_id' => '23', 'course_id' => '143'],
            ['major_id' => '23', 'course_id' => '144'],
            ['major_id' => '23', 'course_id' => '145'],
            //طب بشري
            ['major_id' => '24', 'course_id' => '146'],
            ['major_id' => '24', 'course_id' => '147'],
            ['major_id' => '24', 'course_id' => '148'],
            ['major_id' => '24', 'course_id' => '149'],
            ['major_id' => '24', 'course_id' => '150'],
            ['major_id' => '24', 'course_id' => '151'],
            ['major_id' => '24', 'course_id' => '152'],
            ['major_id' => '24', 'course_id' => '153'],
            ['major_id' => '24', 'course_id' => '154'],
            ['major_id' => '24', 'course_id' => '155'],
            ['major_id' => '24', 'course_id' => '156'],
            ['major_id' => '24', 'course_id' => '157'],
            ['major_id' => '24', 'course_id' => '158'],
            ['major_id' => '24', 'course_id' => '159'],
            ['major_id' => '24', 'course_id' => '160'],
            //علوم طبية مخبرية
            ['major_id' => '25', 'course_id' => '104'],
            ['major_id' => '25', 'course_id' => '151'],
            ['major_id' => '25', 'course_id' => '107'],
            ['major_id' => '25', 'course_id' => '108'],
            ['major_id' => '25', 'course_id' => '109'],
            ['major_id' => '25', 'course_id' => '110'],
            ['major_id' => '25', 'course_id' => '111'],
            ['major_id' => '25', 'course_id' => '112'],
            ['major_id' => '25', 'course_id' => '113'],
            ['major_id' => '25', 'course_id' => '115'],
            ['major_id' => '25', 'course_id' => '116'],
            //طبية حيوية
            ['major_id' => '26', 'course_id' => '104'],
            ['major_id' => '26', 'course_id' => '151'],
            ['major_id' => '26', 'course_id' => '107'],
            ['major_id' => '26', 'course_id' => '108'],
            ['major_id' => '26', 'course_id' => '109'],
            ['major_id' => '26', 'course_id' => '110'],
            ['major_id' => '26', 'course_id' => '111'],
            ['major_id' => '26', 'course_id' => '112'],
            ['major_id' => '26', 'course_id' => '113'],
            ['major_id' => '26', 'course_id' => '115'],
            ['major_id' => '26', 'course_id' => '116'],
            // البصريات
            ['major_id' => '27', 'course_id' => '161'],
            ['major_id' => '27', 'course_id' => '162'],
            ['major_id' => '27', 'course_id' => '163'],
            ['major_id' => '27', 'course_id' => '164'],
            ['major_id' => '27', 'course_id' => '165'],
            ['major_id' => '27', 'course_id' => '166'],
            //القبالة
            ['major_id' => '28', 'course_id' => '167'],
            ['major_id' => '28', 'course_id' => '168'],
            ['major_id' => '28', 'course_id' => '169'],
            ['major_id' => '28', 'course_id' => '110'],
            ['major_id' => '28', 'course_id' => '111'],
            ['major_id' => '28', 'course_id' => '109'],
            ['major_id' => '28', 'course_id' => '132'],
            ['major_id' => '28', 'course_id' => '133'],
            ['major_id' => '28', 'course_id' => '112'],
            ['major_id' => '28', 'course_id' => '113'],
            ['major_id' => '28', 'course_id' => '141'],
            ['major_id' => '28', 'course_id' => '142'],
            ['major_id' => '28', 'course_id' => '143'],
            ['major_id' => '28', 'course_id' => '144'],
            ['major_id' => '28', 'course_id' => '145'],
            //علاج طبيعي
            ['major_id' => '30', 'course_id' => '119'],
            ['major_id' => '30', 'course_id' => '171'],
            ['major_id' => '30', 'course_id' => '172'],
            ['major_id' => '30', 'course_id' => '173'],
            ['major_id' => '30', 'course_id' => '174'],
            ['major_id' => '30', 'course_id' => '175'],
            ['major_id' => '30', 'course_id' => '176'],
            ['major_id' => '30', 'course_id' => '177'],
            ['major_id' => '30', 'course_id' => '178'],
            ['major_id' => '30', 'course_id' => '179'],
            ['major_id' => '30', 'course_id' => '180'],
            ['major_id' => '30', 'course_id' => '181'],
            //علم السكع والنطق
            ['major_id' => '32', 'course_id' => '182'],
            ['major_id' => '32', 'course_id' => '160'],
            ['major_id' => '32', 'course_id' => '183'],
            ['major_id' => '32', 'course_id' => '184'],
            ['major_id' => '32', 'course_id' => '185'],
            ['major_id' => '32', 'course_id' => '186'],
            ['major_id' => '32', 'course_id' => '187'],
            ['major_id' => '32', 'course_id' => '188'],
            ['major_id' => '32', 'course_id' => '189'],
            ['major_id' => '32', 'course_id' => '190'],
            // الفزياء
            ['major_id' => '37', 'course_id' => '1'],
            ['major_id' => '37', 'course_id' => '2'],
            ['major_id' => '37', 'course_id' => '3'],
            ['major_id' => '37', 'course_id' => '4'],
            ['major_id' => '37', 'course_id' => '5'],
            ['major_id' => '37', 'course_id' => '7'],
            ['major_id' => '37', 'course_id' => '8'],
            ['major_id' => '37', 'course_id' => '9'],
            ['major_id' => '37', 'course_id' => '10'],
            ['major_id' => '37', 'course_id' => '191'],
            ['major_id' => '37', 'course_id' => '192'],
            ['major_id' => '37', 'course_id' => '193'],
            ['major_id' => '37', 'course_id' => '194'],
            ['major_id' => '37', 'course_id' => '195'],
            ['major_id' => '37', 'course_id' => '196'],
            ['major_id' => '37', 'course_id' => '197'],
            ['major_id' => '37', 'course_id' => '198'],
            ['major_id' => '37', 'course_id' => '199'],
            ['major_id' => '37', 'course_id' => '200'],
            ['major_id' => '37', 'course_id' => '201'],
            ['major_id' => '37', 'course_id' => '202'],
            ['major_id' => '37', 'course_id' => '203'],
            ['major_id' => '37', 'course_id' => '204'],
            ['major_id' => '37', 'course_id' => '205'],
            ['major_id' => '37', 'course_id' => '206'],
            //محاسبة
            ['major_id' => '46', 'course_id' => '207'],
            ['major_id' => '46', 'course_id' => '208'],
            ['major_id' => '46', 'course_id' => '209'],
            ['major_id' => '46', 'course_id' => '210'],
            ['major_id' => '46', 'course_id' => '211'],
            ['major_id' => '46', 'course_id' => '212'],
            ['major_id' => '46', 'course_id' => '213'],
            ['major_id' => '46', 'course_id' => '214'],
            ['major_id' => '46', 'course_id' => '215'],
            ['major_id' => '46', 'course_id' => '216'],
            ['major_id' => '46', 'course_id' => '217'],
            //التصميم الداخلي
            ['major_id' => '61', 'course_id' => '218'],
            ['major_id' => '61', 'course_id' => '219'],
            ['major_id' => '61', 'course_id' => '220'],
            ['major_id' => '61', 'course_id' => '221'],
        ];
        DB::table('major_courses')->insert($relation);

        // $files = [
        //     ['name' => 'الكتاب + الحلول' ,'path' => 'https://drive.google.com/drive/folders/1FsiLKO72GyAlz62lFofFSaY_ZClytQxm?fbclid=IwAR2g_0u1MIhccouY2pKJ4WQWboSraQdelRgzrPRzpQsLlR195J2X9bRFjBk', 'collage_id' => '1'],
        //     ['name' => 'سلايدات د.عدنان' ,'path' => 'https://drive.google.com/drive/folders/1YabIKiY2yWg81nzwFByd3EaaTem3vHdD?fbclid=IwAR2g_0u1MIhccouY2pKJ4WQWboSraQdelRgzrPRzpQsLlR195J2X9bRFjBk', 'collage_id' => '1'],
        //     ['name' => 'محاضرات د.عدنان' ,'path' => 'https://drive.google.com/drive/folders/1cqBb-PBl5X3KJaHKPmVyywnrPSDXKBJF?usp=sharing', 'collage_id' => '1'],
        //     ['name' => 'فيرست كالك 1' ,'path' => 'https://drive.google.com/drive/folders/1CnV_tCi9nkQsKxcuwpmZJv3-rx-ljN89?fbclid=IwAR2g_0u1MIhccouY2pKJ4WQWboSraQdelRgzrPRzpQsLlR195J2X9bRFjBk', 'collage_id' => '1'],
        //     ['name' => 'سكند كالك 1' ,'path' => 'https://drive.google.com/drive/folders/1fa9YbPmA1vQE8t8HlDewPNA01jYabjR3?fbclid=IwAR2g_0u1MIhccouY2pKJ4WQWboSraQdelRgzrPRzpQsLlR195J2X9bRFjBk', 'collage_id' => '1'],
        //     ['name' => 'فاينل كالك 1' ,'path' => 'https://drive.google.com/drive/folders/1ZCV1qIanQlze7z3L14U4p9F8nRICAwDe?fbclid=IwAR2g_0u1MIhccouY2pKJ4WQWboSraQdelRgzrPRzpQsLlR195J2X9bRFjBk', 'collage_id' => '1'],
        //     ['name' => 'تلخيص د.باسم مصطفى' ,'path' => 'https://drive.google.com/drive/folders/1XF87e57R3jtNe83SoLZh1gKQkCw2Pq_T?fbclid=IwAR2g_0u1MIhccouY2pKJ4WQWboSraQdelRgzrPRzpQsLlR195J2X9bRFjBk', 'collage_id' => '1'],
        //     ['name' => 'سلايدات مقدمة', 'path' => 'https://drive.google.com/drive/folders/1LhUwvN2dL9LfhZHvKWioczsYb2nTjaMR?usp=sharing', 'collage_id' => '6'], 
        //     ['name' => 'كتاب احصاء واحتمالات', 'path' => 'https://drive.google.com/drive/folders/15wqqhIR8A3uOZ6w9MHjkeekorsXPNfmx?usp=sharing', 'collage_id' => '6'], 
        //     ['name' => 'سلايدات احصاء واحتمالات', 'path' => 'https://drive.google.com/drive/folders/1EnqG2pgSKQW-sKO9lQZ8qR_6kfgz0ARZ?usp=sharing', 'collage_id' => '6'], 
        //     ['name' => 'كتاب محاسبة', 'path' => 'https://drive.google.com/drive/folders/1j-FDtgECkiFP4Ktyg-Ag4eWWyV16gVnk?usp=sharing', 'collage_id' => '6'], 
        //     //دسكريت
        //     ['name' => 'الكتاب + الحلول', 'path' => 'https://drive.google.com/drive/folders/1QJrsl3gfkBk1MzAV3JsIk22_jSVGJFFS?usp=sharing', 'collage_id' => '6'], 
        //     ['name' => 'سلايدات دسكريت', 'path' => 'https://drive.google.com/drive/folders/1M2eQn3bA-iRH67SJqMAVIHzFv6-VS8MQ?usp=sharing', 'collage_id' => '6'], 
        //     ['name' => 'فيرست دسكريت', 'path' => 'https://drive.google.com/drive/folders/1wHjVYN6ivLAuptK6A87SxzsUJAt4QI94?usp=sharing', 'collage_id' => '6'], 
        //     ['name' => 'سكند دسكريت', 'path' => 'https://drive.google.com/drive/folders/1K_qnyqBzXRGxRoudsfoCZQ5gR2A1MKkA?usp=sharing', 'collage_id' => '6'], 
        //     ['name' => 'فاينل دسكريت', 'path' => 'https://drive.google.com/drive/folders/1IPMgdvIubnGbwlyVQc4FAWoeHauAnygA?usp=sharing', 'collage_id' => '6'], 
        //     ['name' => 'محاضرات د.عبدالله', 'path' => 'https://drive.google.com/drive/folders/15GpkiNVSKu71ZJQNT45WsNd2Q3y_9SmM?usp=sharing', 'collage_id' => '6'], 
        //     //فيزياء عامة 1
        //     ['name' => 'الكتاب + الحلول', 'path' => 'https://drive.google.com/drive/folders/1A6OEWxitxX5RwJOuGDNsc-KEz0_yBU9Y?usp=sharing', 'collage_id' => '6'], 
        //     ['name' => 'سلايدات د.معن', 'path' => 'https://drive.google.com/drive/folders/1ATHLEZXfOBn0V0XcsYt9vy8_WwRjL8np?usp=sharing', 'collage_id' => '6'], 
        //     ['name' => 'محاضرات مصورة', 'path' => 'https://www.youtube.com/watch?v=DTg8-RmQglw&list=PLxAmLxkixn_mm9S-TfXUsUJrjYniXwY9p', 'collage_id' => '6'], 
        //     ['name' => 'سلايدات فيزياء 1', 'path' => 'https://drive.google.com/drive/folders/1kAyi9b4xCIiMYsQtQHtehponblqnkNkz?usp=sharing', 'collage_id' => '6'], 
        //     ['name' => 'فيرست فيزياء 1', 'path' => 'https://drive.google.com/drive/folders/1oqy5WrYWMVQSBgMXy0Nzi3NhCwiHae6W?usp=sharing', 'collage_id' => '6'], 
        //     ['name' => 'سكند فيزياء 1', 'path' => 'https://drive.google.com/drive/folders/1T3o-roDw8FYtRBz0doA3HvpIkbG1M4NF?usp=sharing', 'collage_id' => '6'], 
        //     ['name' => 'فاينل فيزياء 1', 'path' => 'https://drive.google.com/drive/folders/1HvNH9WNXe4Fe7C5Vg5LGEhuO44uMSX7m?fbclid=IwAR2g_0u1MIhccouY2pKJ4WQWboSraQdelRgzrPRzpQsLlR195J2X9bRFjBk', 'collage_id' => '6'], 
        //     ['name' => 'محاضرات د.اياد', 'path' => 'https://mega.nz/folder/0jZUzRYD#sMfvLe8J6wTGeTXIuRFzRw', 'collage_id' => '6'], 
        //     ['name' => 'محاضرات د.معن', 'path' => 'https://docs.google.com/document/d/163ZxD3mXkbCIrYugPo9wHQcGGTjHzBpGhuexZ3kPcvQ/edit?fbclid=IwAR2Jg9kbFM40uCFV8nYC5_9iqHbHpLtxjWD36hd0uHW3sF2NO87MNIQHkwo', 'collage_id' => '6'], 
        //     //فيزياء عامة 2
        //     ['name' => 'الكتاب + الحلول', 'path' => 'https://drive.google.com/drive/folders/1A6OEWxitxX5RwJOuGDNsc-KEz0_yBU9Y?fbclid=IwAR2g_0u1MIhccouY2pKJ4WQWboSraQdelRgzrPRzpQsLlR195J2X9bRFjBk', 'collage_id' => '6'], 
        //     ['name' => 'سلايدات فيزياء 2', 'path' => 'https://drive.google.com/drive/folders/1tHYMRC9I5R3VaCB9JNbgVRjh-_xZ8FSd?fbclid=IwAR2g_0u1MIhccouY2pKJ4WQWboSraQdelRgzrPRzpQsLlR195J2X9bRFjBk', 'collage_id' => '6'], 
        //     ['name' => 'محاضرات مصورة', 'path' => 'https://drive.google.com/drive/folders/1Td4QZmZ5c2hfXxp7VXIowRR_c4aocZQD?fbclid=IwAR2g_0u1MIhccouY2pKJ4WQWboSraQdelRgzrPRzpQsLlR195J2X9bRFjBk', 'collage_id' => '6'], 
        //     ['name' => 'فيرست فيزياء 2', 'path' => 'https://drive.google.com/drive/folders/1Bgc9iWkN6JGrwC0-iMncSNF5Q_P7iXV1?fbclid=IwAR2g_0u1MIhccouY2pKJ4WQWboSraQdelRgzrPRzpQsLlR195J2X9bRFjBk', 'collage_id' => '6'], 
        //     ['name' => 'سكند فيزياء 2', 'path' => 'https://drive.google.com/drive/folders/1i-OqEeffrG_L-aUUhZyFjmgfhIPUspeO?fbclid=IwAR2g_0u1MIhccouY2pKJ4WQWboSraQdelRgzrPRzpQsLlR195J2X9bRFjBk', 'collage_id' => '6'], 
        //     ['name' => 'فاينل فيزياء 2', 'path' => 'https://drive.google.com/drive/folders/1Th1NLbtCUgJumxrOuPVUeBvlCZX3gMpd?usp=sharing', 'collage_id' => '6'], 
        //     ['name' => 'الكتروني فيزياء 2', 'path' => 'https://drive.google.com/drive/folders/19ovPfYW2kwWW3dbYG63mQdK0r6LrYaN6?fbclid=IwAR2g_0u1MIhccouY2pKJ4WQWboSraQdelRgzrPRzpQsLlR195J2X9bRFjBk', 'collage_id' => '6'], 
        //     // مختبر فزياء للهندسة
        //     ['name' => 'تلخيص قوانين المختبر', 'path' => 'https://drive.google.com/drive/u/0/folders/19lEZwnqP5apPV4FVEWSzIxA65SqOxdK_', 'collage_id' => '6'], 
        //     ['name' => 'فيديوهات للتجارب', 'path' => 'https://www.youtube.com/channel/UCneA-eaL57ed7-ge33xF39Q', 'collage_id' => '6'], 
        //     ['name' => 'فاينل مختبر الفيزياء', 'path' => 'https://drive.google.com/drive/u/0/folders/1lGY42gDIz3L6dVtmEoTI_1bSgmkHEfxy', 'collage_id' => '6'], 
        //     ['name' => 'تقارير مختبر الفيزياء', 'path' => 'https://drive.google.com/drive/u/0/folders/1QmqLRFKO72NQo074iDz5Xm9p9YpJsvQv', 'collage_id' => '6'], 
        //     //كيمياء عامة 1
        //     ['name' => 'الكتاب + الحلول', 'path' => 'https://drive.google.com/drive/folders/1ejixONDgGw-32wM2JqlhOytPJuvGHveT?usp=sharing', 'collage_id' => '6'], 
        //     ['name' => 'سلايدات د.رندة', 'path' => 'https://drive.google.com/drive/u/0/folders/1T1Qv3Zb9mId5hJhtFQdef15GGq1cy-so', 'collage_id' => '6'], 
        //     ['name' => 'محاضرات مصورة', 'path' => 'https://drive.google.com/drive/folders/19Fqssnz14QkgJEAqPRLxBdt9PhgPFlGq?usp=sharing', 'collage_id' => '6'], 
        //     ['name' => 'دفتر كيمياء 1', 'path' => 'https://drive.google.com/drive/u/0/folders/1hMXnpWbSRWQ0OdscToAA5t6SI5gRKZHp', 'collage_id' => '6'], 
        //     ['name' => 'امتحانات وجاهية', 'path' => 'https://drive.google.com/drive/u/0/folders/1mm8goCcjH6lS1_osuEbh-MOacZmQqsEz', 'collage_id' => '6'], 
        //     ['name' => 'امتحانات الكترونية', 'path' => 'https://drive.google.com/drive/u/0/folders/1jBxteGNoafEJD_U2bW1WIPl9o2AbBftm', 'collage_id' => '6'], 
        //     ['name' => 'الجدول الدوري', 'path' => 'https://drive.google.com/drive/u/0/folders/1dZwnG19Ap3ex_nvKtq2fhg3nw8Hx594S', 'collage_id' => '6'], 
        //     //مختبر كيمياء
        //     ['name' => 'تقارير مختبر كيمياء 1', 'path' => 'https://drive.google.com/drive/u/0/folders/1B7PYpAsgM1zkgLw7X-BQ_WXwC-mkZ5Ua', 'collage_id' => '6'], 
        //     ['name' => 'قوانين مختبر الكيمياء', 'path' => 'https://drive.google.com/drive/u/0/folders/1nyteb0hJVlzOKkYTaSElb0ufR2sewkBl', 'collage_id' => '6'], 
        //     ['name' => 'امتحانات المختبر', 'path' => 'https://drive.google.com/drive/u/0/folders/1_q1L8Mp1smNOUdcDSYgHnbwRtrM6JoaA', 'collage_id' => '6'], 
        //     //رسم هندسي
        //     ['name' => 'دوسية الرسم الهندسي', 'path' => 'https://drive.google.com/drive/u/0/folders/1BqsXlUuP_D2R6ncibklmCy4yGLFbf7Dn', 'collage_id' => '6'], 
        //     ['name' => 'شرح دوسية الرسم', 'path' => 'https://drive.google.com/drive/u/0/folders/1e70GKsbtC-r4OMaG5GXd78Nm4YnF5QV4', 'collage_id' => '6'], 
        //     ['name' => 'فاينل رسم هندسي', 'path' => 'https://drive.google.com/drive/u/0/folders/1lEKhSoCewQ2vWGfsEWkwLuJKO2wiD3z9', 'collage_id' => '6'], 
        //     //برمجة الحاسوب
        //     ['name' => 'سلايدات برمجة حاسوب', 'path' => 'https://drive.google.com/drive/u/0/folders/1NRoQJjxDwV9akLSYZxBsZD80PSVoilmX', 'collage_id' => '6'], 
        //     ['name' => 'محاضرات مصورة', 'path' => 'https://drive.google.com/drive/folders/1kL5ml986UKMxroL47_EZZpn1dDDr27iC?usp=sharing', 'collage_id' => '6'], 
        //     ['name' => 'شرح يوتيوب', 'path' => 'https://www.youtube.com/watch?v=z1FdInL8sjg&list=PLCInYL3l2AajFAiw4s1U4QbGszcQ-rAb3', 'collage_id' => '6'], 
        //     ['name' => 'تلخيص مادة الفيرست', 'path' => 'https://drive.google.com/drive/folders/1eB6V5iXGbG1JuHkD3L4M4E72y52-wUDv?usp=sharing', 'collage_id' => '6'], 
        //     ['name' => 'تلخيص مادة السكند', 'path' => 'https://drive.google.com/drive/u/0/folders/1v2c2_mf-KCN3Uh7TktiadUTQMIgXNHKx', 'collage_id' => '6'], 
        //     ['name' => 'تلخيص مادة الفاينل', 'path' => 'https://drive.google.com/drive/u/0/folders/1jSCIweldVUry0ou5cOF2NfRMwtNnk4aM', 'collage_id' => '6'], 
        //     ['name' => 'امتحانات وجاهية', 'path' => 'https://drive.google.com/drive/u/0/folders/1VJCyppD12kDsRk4xXKpCOCJEOXhH0x2s', 'collage_id' => '6'], 
        //     //ديفرنشال
        //     ['name' => 'الكتاب النسخة العاشرة', 'path' => 'https://drive.google.com/drive/folders/1mUOXo-AK_4-s2l6Y3VtRGy53oy9B58yF?usp=sharing', 'collage_id' => '6'], 
        //     ['name' => 'سلايدات ديفرنشال', 'path' => 'https://drive.google.com/drive/folders/11jM5ITKuPtajPDKqOhnKhjoFlp3-0vCy?usp=sharing', 'collage_id' => '6'], 
        //     ['name' => 'امتحانات وجاهية', 'path' => 'https://drive.google.com/drive/folders/1IAoGALt9BVLj8x5AMu5ZYPIok3f3Jij4?fbclid=IwAR3yQ1t1OYa-F2gV0M9Nz1PoQykhZiqjKeooozdY2U-0ax1qS9wtH5KhLzA', 'collage_id' => '6'], 
        //     ['name' => 'محاضرات د.عدنان', 'path' => 'https://drive.google.com/file/d/1gUWh5wL2nV0rBwRXkeSN1G-0KXjTGLVM/view?fbclid=IwAR3yywm_MKta0-bEoTDR1uOub8661hwSXI15ESFQEP67h0OGjq-G2Q7IKuc', 'collage_id' => '6'], 
        //     ['name' => 'محاضرات د.هادي حمد', 'path' => 'https://drive.google.com/drive/folders/1k14sVG0QO5Leyb9QkDr6_V9lFkClaZUW?usp=sharing', 'collage_id' => '6'], 
        //     ['name' => 'محاضرات د.فرحان', 'path' => 'https://drive.google.com/drive/folders/1F2LiLYl_z0bPzMoSVBxoX2O5H5cxs_ny?usp=sharing', 'collage_id' => '6'], 
        //     ['name' => 'امتحانات الكترونية', 'path' => 'https://drive.google.com/drive/folders/1zy0KNT4kLKkDaegLkaHJyRvGej4RisUI?fbclid=IwAR3yQ1t1OYa-F2gV0M9Nz1PoQykhZiqjKeooozdY2U-0ax1qS9wtH5KhLzA', 'collage_id' => '6'], 
        //     ['name' => 'تلاخيص دفرنشال', 'path' => 'https://drive.google.com/drive/folders/1QuEsxvnnH_9SELKUXUpWuS-kyv05s92O?fbclid=IwAR3yQ1t1OYa-F2gV0M9Nz1PoQykhZiqjKeooozdY2U-0ax1qS9wtH5KhLzA', 'collage_id' => '6'], 
        //     //نيوماريكال
        //     ['name' => 'فيرست نيوماريكال', 'path' => 'https://drive.google.com/drive/folders/1pIf8f_MyrwaTT0czKAFAM9i7NSXF8D9M?fbclid=IwAR1DvrsmjDGYrsQCOv7fPeFRjQilXChA7j1kcSkOWznL3T_1HsVj0V4oaEk', 'collage_id' => '6'], 
        //     ['name' => 'سكند نيوماريكال', 'path' => 'https://drive.google.com/drive/folders/1Q-743Dm3l5TFcIE3VZEqaNcvLmaiJ3hp?fbclid=IwAR1DvrsmjDGYrsQCOv7fPeFRjQilXChA7j1kcSkOWznL3T_1HsVj0V4oaEk', 'collage_id' => '6'], 
        //     ['name' => 'قاينل نيوماريكال', 'path' => 'https://drive.google.com/drive/folders/1ys57q3nbx5834SCHCVGwvdvNBoxbImFy?fbclid=IwAR1DvrsmjDGYrsQCOv7fPeFRjQilXChA7j1kcSkOWznL3T_1HsVj0V4oaEk', 'collage_id' => '6'], 
        //     ['name' => '', 'path' => '', 'collage_id' => '6'], 
        //     ['name' => '', 'path' => '', 'collage_id' => '6'], 
        //     ['name' => '', 'path' => '', 'collage_id' => '6'], 
        //     ['name' => '', 'path' => '', 'collage_id' => '6'], 
        //     //اسمبلي
        //     ['name' => 'كتاب الاسمبلي', 'path' => 'https://drive.google.com/drive/folders/1XcR2iLjjXpe8p54ZxaLd4f-ZjpMiEJTo', 'collage_id' => '6'], 
        //     ['name' => 'سلايدات اسمبلي', 'path' => 'https://drive.google.com/drive/folders/1kL7QEsklUB4vLwjhPCxdXzS-PJ7Xt7PS', 'collage_id' => '6'], 
        //     ['name' => 'سكند اسمبلي', 'path' => 'https://drive.google.com/drive/folders/1uuiCF2wrxRGCDVGfTMdzgudWmKm9xRbn', 'collage_id' => '6'], 
        //     ['name' => 'تلاخيص اسمبلي', 'path' => 'https://www.mediafire.com/folder/3gzq02zx3kear/%D8%AA%D9%84%D8%AE%D9%8A%D8%B5%D8%A7%D8%AA', 'collage_id' => '6'], 
        //     //سيكيورتي
        //     ['name' => 'سلايدات سكيورتي', 'path' => 'https://drive.google.com/drive/folders/1uE4THdWNXbpVwL8JDnmtMUZOiselXb9u?fbclid=IwAR2jyJaaF8JzOcaTOZ4jBEwl6cPExy8QttnnpQMiiMAqhUAMVRMz0XcrEmM', 'collage_id' => '6'], 
        //     //تركيب البيانات
        //     ['name' => 'سلايدات تركيب البيانات', 'path' => 'https://drive.google.com/drive/folders/1pAMy4cWZXQ0OTrdS0SVPkfsWT3GOakHH', 'collage_id' => '6'], 
        //     //اساسيات البرمجة الكينونية
        //     ['name' => 'سلايدات البرمجة الكينونية', 'path' => 'https://drive.google.com/drive/folders/1x8YslWzGID_UDINjYh-vA6P0d3NzDHRY', 'collage_id' => '6'], 
        //     //كتابة تقارير فنية
        //     ['name' => 'كتاب تقارير فنية', 'path' => 'https://drive.google.com/drive/folders/1bneEq_C6xeaJOyIArujUnP5R9q9nTumI?usp=sharing', 'collage_id' => '6'], 
        //     ['name' => 'سلايدات تقارير فنية', 'path' => 'https://drive.google.com/drive/folders/1GfXLzgWFNwI-MknD2Lx93o5uAQToYE1r?usp=sharing', 'collage_id' => '6'], 
        //     //وايرلس
        //     ['name' => 'كتاب وايرليس', 'path' => 'https://drive.google.com/drive/folders/1Q9dVV8wy4zffljrA4QfvPtq_0-nLdCMK?usp=sharing', 'collage_id' => '6'],
        //     ['name' => 'سلايدات وايرليس', 'path' => 'https://drive.google.com/drive/folders/1RomSMuvSYIhsh4TRz4nornZ9lg2SG655?usp=sharing', 'collage_id' => '6'], 
        //     //كالك 2
        //     ['name' => 'الكتاب + الحلول', 'path' => 'https://drive.google.com/drive/folders/1FsiLKO72GyAlz62lFofFSaY_ZClytQxm?fbclid=IwAR2g_0u1MIhccouY2pKJ4WQWboSraQdelRgzrPRzpQsLlR195J2X9bRFjBk', 'collage_id' => '6'], 
        //     ['name' => 'سلايدات كالك 2', 'path' => 'https://drive.google.com/drive/folders/1Mt4WjHawAeP1TgREsA7LRWPMoc426uJe?fbclid=IwAR2g_0u1MIhccouY2pKJ4WQWboSraQdelRgzrPRzpQsLlR195J2X9bRFjBk', 'collage_id' => '6'], 
        //     ['name' => 'محاضرات د.عدنان', 'path' => 'https://drive.google.com/drive/folders/1wB4x-fKc8XapIKm5RSOnDiXI4wJFn2EZ?usp=sharing', 'collage_id' => '6'], 
        //     ['name' => 'فيرست كالك 2', 'path' => 'https://drive.google.com/drive/folders/1NTbqdEP9z29q-2YeiFcBJaCLjQBgdPCY?fbclid=IwAR2g_0u1MIhccouY2pKJ4WQWboSraQdelRgzrPRzpQsLlR195J2X9bRFjBk', 'collage_id' => '6'], 
        //     ['name' => 'سكند كالك 2', 'path' => 'https://drive.google.com/drive/folders/1kVddEsUSe-GWvo2xMATjFFqHxm3tL0sI?fbclid=IwAR2g_0u1MIhccouY2pKJ4WQWboSraQdelRgzrPRzpQsLlR195J2X9bRFjBk', 'collage_id' => '6'], 
        //     ['name' => 'فاينل كالك 2', 'path' => 'https://drive.google.com/drive/folders/1io1PXDqQs4Xn8zC_Hb77GjzPSgtha0Hn?fbclid=IwAR2g_0u1MIhccouY2pKJ4WQWboSraQdelRgzrPRzpQsLlR195J2X9bRFjBk', 'collage_id' => '6'], 
        //     ['name' => 'ميدتيرم كالك 2', 'path' => 'https://drive.google.com/drive/folders/17gFkAXg5rXJXaQCiLq_dHvaTo3LW0IhW?fbclid=IwAR2g_0u1MIhccouY2pKJ4WQWboSraQdelRgzrPRzpQsLlR195J2X9bRFjBk', 'collage_id' => '6'], 
        //     ['name' => 'اسايمنت اول', 'path' => 'https://drive.google.com/drive/folders/1DHwXAzrUXFOee-5JUS5bI2X4inoggj-g?fbclid=IwAR2g_0u1MIhccouY2pKJ4WQWboSraQdelRgzrPRzpQsLlR195J2X9bRFjBk', 'collage_id' => '6'], 
        //     ['name' => 'اسايمنت ثاني', 'path' => 'https://drive.google.com/drive/folders/1bfIvsD1nVzHx_VZbZj3ZLam8vRwyXtGi?fbclid=IwAR2g_0u1MIhccouY2pKJ4WQWboSraQdelRgzrPRzpQsLlR195J2X9bRFjBk', 'collage_id' => '6'], 
        //     ['name' => 'تلخيص كالك 2', 'path' => 'https://drive.google.com/drive/folders/1ItBL-2Y2uhPqYWtqrwNHDyqZcG6N0nep?fbclid=IwAR2g_0u1MIhccouY2pKJ4WQWboSraQdelRgzrPRzpQsLlR195J2X9bRFjBk', 'collage_id' => '6'], 
        //     //كالك 3
        //     ['name' => 'الكتاب + الحلول', 'path' => 'https://drive.google.com/drive/folders/1FsiLKO72GyAlz62lFofFSaY_ZClytQxm?fbclid=IwAR2g_0u1MIhccouY2pKJ4WQWboSraQdelRgzrPRzpQsLlR195J2X9bRFjBk', 'collage_id' => '6'], 
        //     ['name' => 'سلايدات كالك 3', 'path' => 'https://drive.google.com/drive/folders/1eTIYTB0SfFoYGr17GFfAQFW9cq6oN5v6?fbclid=IwAR2g_0u1MIhccouY2pKJ4WQWboSraQdelRgzrPRzpQsLlR195J2X9bRFjBk', 'collage_id' => '6'], 
        //     ['name' => 'فيرست كالك 3', 'path' => 'https://drive.google.com/drive/folders/1-MWMxASUEUm_zb6XVNNmMy7nlJheXj-e?fbclid=IwAR2g_0u1MIhccouY2pKJ4WQWboSraQdelRgzrPRzpQsLlR195J2X9bRFjBk', 'collage_id' => '6'], 
        //     ['name' => 'محاضرات مصورة', 'path' => 'https://drive.google.com/drive/folders/1bUkXoYesX2oKJXATNTbigvqHDFhR334q?usp=sharing', 'collage_id' => '6'], 
        //     ['name' => 'سكند كالك 3', 'path' => 'https://drive.google.com/drive/folders/1sibLeeovze-N60mEDstHPDToCUM0XbF-?fbclid=IwAR2g_0u1MIhccouY2pKJ4WQWboSraQdelRgzrPRzpQsLlR195J2X9bRFjBk', 'collage_id' => '6'], 
        //     ['name' => 'فاينل كالك 3', 'path' => 'https://drive.google.com/drive/folders/1mduERlNWjkaT4re3eUI0E1pwwsPj-dAo?fbclid=IwAR2g_0u1MIhccouY2pKJ4WQWboSraQdelRgzrPRzpQsLlR195J2X9bRFjBk', 'collage_id' => '6'], 
        //     ['name' => 'تلخيص كالك 3', 'path' => 'https://drive.google.com/drive/folders/1JajS0dUBNDDMUX2NhtOdIMtFXAFb3sl-?fbclid=IwAR2g_0u1MIhccouY2pKJ4WQWboSraQdelRgzrPRzpQsLlR195J2X9bRFjBk', 'collage_id' => '6'], 
        //     //ميكانيكا هندسية
        //     ['name' => 'تلخيص ميكانيكا هندسة', 'path' => 'https://drive.google.com/drive/u/0/folders/1O7ZX-Ql7CS_hpRGTG3efTxrXcCmr-Pvf', 'collage_id' => '6'], 
        //     ['name' => 'فيرست ميكانيكا هندسية', 'path' => 'https://drive.google.com/drive/u/0/folders/1dGYsZYBWQxXgTHgvwmYH2bYhOmY9IIOK', 'collage_id' => '6'], 
        //     ['name' => 'سكند ميكانيكا هندسية', 'path' => 'https://drive.google.com/drive/u/0/folders/1kU1E3Zaa3VATsvDc5MQc5xNWxW_VePie', 'collage_id' => '6'], 
        //     // مبادئ الاتصالات
        //     ['name' => 'تلخيص الفيرست', 'path' => 'https://drive.google.com/file/d/1hgVnubPVyBszD_24SZAmAVQLbY9kpIpJ/view', 'collage_id' => '6'], 
        //     ['name' => 'تلخيص السكند', 'path' => 'https://drive.google.com/file/d/1bzGMfkjMMvw3x7orBiGzrx_sB4Wq4_73/view', 'collage_id' => '6'], 
        //     ['name' => 'تلخيص الفاينل', 'path' => 'https://drive.google.com/file/d/1lpDk9DrlMesn9CkRR4qBO6cP0Ca4We18/view', 'collage_id' => '6'], 
        //     ['name' => 'امتحانات الفيرست', 'path' => 'https://drive.google.com/drive/folders/1n_zeAm0OxagMAYg_I2JECRa0C2HFcHlK?fbclid=IwAR1DvrsmjDGYrsQCOv7fPeFRjQilXChA7j1kcSkOWznL3T_1HsVj0V4oaEk', 'collage_id' => '6'], 
        //     ['name' => 'امتحانات السكند', 'path' => 'https://drive.google.com/drive/folders/1wd_JrCPvheF6PbLVia8mF7SfSLxo9kbg?fbclid=IwAR1DvrsmjDGYrsQCOv7fPeFRjQilXChA7j1kcSkOWznL3T_1HsVj0V4oaEk', 'collage_id' => '6'], 
        //     ['name' => 'امتحانات الفاينل', 'path' => 'https://drive.google.com/drive/folders/1OWZY2jUb_8hg8qdiSpcmpXa4Ro8RTErF?fbclid=IwAR1DvrsmjDGYrsQCOv7fPeFRjQilXChA7j1kcSkOWznL3T_1HsVj0V4oaEk', 'collage_id' => '6'], 
        //     //ديجتال 
        //     ['name' => 'الكتاب النسخة الرابعة', 'path' => 'https://drive.google.com/drive/folders/1gogbWHhNtEGvynv-20DlfiTYoPvGyx1Y?fbclid=IwAR2BJtpFqEllUEvyfZqSFLPae4iXccuyEjK8wzqjvaJucJPb1fPHNb8R508', 'collage_id' => '6'], 
        //     ['name' => 'سلايدات د. عماد', 'path' => 'https://drive.google.com/drive/folders/1jk3JG67ioGx3PoIq3jBZFqsnsc8GaTgN?fbclid=IwAR2BJtpFqEllUEvyfZqSFLPae4iXccuyEjK8wzqjvaJucJPb1fPHNb8R508', 'collage_id' => '6'], 
        //     ['name' => 'محاضرات مصورة', 'path' => 'https://drive.google.com/drive/folders/1lDzS0wwAUPXi3zg3XsjMU01VQ8nFycDL?usp=sharing', 'collage_id' => '6'], 
        //     ['name' => 'واجبات + الحلول', 'path' => 'https://drive.google.com/drive/folders/1465nTaEzmOMvEznqzele6Np4V0KcBUcQ?fbclid=IwAR2BJtpFqEllUEvyfZqSFLPae4iXccuyEjK8wzqjvaJucJPb1fPHNb8R508', 'collage_id' => '6'], 
        //     ['name' => 'امتحانات وجاهية', 'path' => 'https://drive.google.com/drive/folders/1T1JPhVlte7uMYiNxr42db6KZPVv3p6Gr?fbclid=IwAR2BJtpFqEllUEvyfZqSFLPae4iXccuyEjK8wzqjvaJucJPb1fPHNb8R508', 'collage_id' => '6'], 
        //     //مختبر ديجتال
        //     ['name' => 'سلايدات المختبر', 'path' => 'https://drive.google.com/drive/folders/12fK7xaihdSapCUGPV9bKwyPE9gqlJpGr?usp=sharing', 'collage_id' => '6'], 
        //     ['name' => 'تقارير المختبر', 'path' => 'https://drive.google.com/drive/folders/1Rx4kt5cEjXtpT1L5jy9o6zC5pfb1hDq2?fbclid=IwAR2BJtpFqEllUEvyfZqSFLPae4iXccuyEjK8wzqjvaJucJPb1fPHNb8R508', 'collage_id' => '6'], 
        //     ['name' => 'تلخيص مختبر ', 'path' => 'https://drive.google.com/drive/folders/12XMsCTgIcigdq5y_McqpYaLsYljeCH6v?fbclid=IwAR2BJtpFqEllUEvyfZqSFLPae4iXccuyEjK8wzqjvaJucJPb1fPHNb8R508', 'collage_id' => '6'], 
        //     ['name' => 'نماذج فاينل', 'path' => 'https://drive.google.com/drive/folders/1dgSiyCJeSjML9e7GM5b8R1pJ-FVN9yIx?fbclid=IwAR2BJtpFqEllUEvyfZqSFLPae4iXccuyEjK8wzqjvaJucJPb1fPHNb8R508', 'collage_id' => '6'], 
        //     ['name' => 'تجارب ديج 1', 'path' => 'https://drive.google.com/drive/folders/1_JEzIdXXT0Sc9GlgFQXbifKg8CvHvuwW?usp=sharing', 'collage_id' => '6'], 
        //     //كهرو 1
        //     ['name' => 'تلخيص فيرست', 'path' => 'https://drive.google.com/file/d/1_OJ9vxpwENff0vkLSivJBtuJaCemoaIf/view', 'collage_id' => '6'], 
        //     ['name' => 'تلخيص سكند', 'path' => 'https://drive.google.com/file/d/1-l2LcV16Jn-G0DVskH2A5Gw0oLMlL6CP/view', 'collage_id' => '6'], 
        //     ['name' => 'تلخيص فاينل', 'path' => 'https://drive.google.com/file/d/13-f7Kn1M116vKETz-EYuGvypt1ZE8w_W/view', 'collage_id' => '6'], 
        //     ['name' => 'فيرست كهرو 1', 'path' => 'https://drive.google.com/drive/folders/1cAjRpAq6KDv_fd5pxu5HyBrKTT2iXq74?fbclid=IwAR1DvrsmjDGYrsQCOv7fPeFRjQilXChA7j1kcSkOWznL3T_1HsVj0V4oaEk', 'collage_id' => '6'], 
        //     ['name' => 'سكند كهرو 1', 'path' => 'https://drive.google.com/drive/folders/1-Dtk6JWQnZcCkTmicTNyYVCzd0xxUDWP?fbclid=IwAR1DvrsmjDGYrsQCOv7fPeFRjQilXChA7j1kcSkOWznL3T_1HsVj0V4oaEk', 'collage_id' => '6'], 
        //     //كهرو 2
        //     ['name' => 'فيرست كهرو 2', 'path' => 'https://drive.google.com/drive/folders/16GNEH7N-RX7ZMjZW3RVrfBbM8IY1onYQ?fbclid=IwAR1DvrsmjDGYrsQCOv7fPeFRjQilXChA7j1kcSkOWznL3T_1HsVj0V4oaEk', 'collage_id' => '6'], 
        //     ['name' => 'سكند كهرو 2', 'path' => 'https://drive.google.com/drive/folders/1WhUJTAyUG4CmaSkj8-7xkGsTGUAs4fdI?fbclid=IwAR1DvrsmjDGYrsQCOv7fPeFRjQilXChA7j1kcSkOWznL3T_1HsVj0V4oaEk', 'collage_id' => '6'], 
        //     //كنترول
        //     ['name' => 'تلخيص كونترول', 'path' => 'https://drive.google.com/drive/folders/1rXV6qNHas2o6tOaDP9IBNDYXwibJhWFD?fbclid=IwAR1DvrsmjDGYrsQCOv7fPeFRjQilXChA7j1kcSkOWznL3T_1HsVj0V4oaEk', 'collage_id' => '6'], 
        //     ['name' => 'فيرست كونترول', 'path' => 'https://drive.google.com/drive/folders/13mPtF4dMDzepa5xNv032E7BoM1aBYxsK?fbclid=IwAR1DvrsmjDGYrsQCOv7fPeFRjQilXChA7j1kcSkOWznL3T_1HsVj0V4oaEk', 'collage_id' => '6'], 
        //     ['name' => 'سكند كونترول', 'path' => 'https://drive.google.com/drive/folders/1LNmkBXiQj-SjdMXHMWU6swMos13ayEfx?fbclid=IwAR1DvrsmjDGYrsQCOv7fPeFRjQilXChA7j1kcSkOWznL3T_1HsVj0V4oaEk', 'collage_id' => '6'], 
        //     ['name' => 'فاينل كونترول', 'path' => 'https://drive.google.com/drive/folders/1si5prMxk6gatJ5YTAw9VlPi8Z94Ttu6A?fbclid=IwAR1DvrsmjDGYrsQCOv7fPeFRjQilXChA7j1kcSkOWznL3T_1HsVj0V4oaEk', 'collage_id' => '6'], 
        //     //مختبر الكونترول
        //     ['name' => 'اسئلة سنوات', 'path' => 'https://drive.google.com/drive/folders/1U6OkfGgzZIbDfJwquOtVDJYztrCGWIOD?fbclid=IwAR1DvrsmjDGYrsQCOv7fPeFRjQilXChA7j1kcSkOWznL3T_1HsVj0V4oaEk', 'collage_id' => '6'], 
        //     // الكترونية 1
        //     ['name' => 'سلايدات الكترونية 1', 'path' => 'https://drive.google.com/drive/folders/1lfBZBKjqriu8MrQzbPA4drYgpt5CjIzA?fbclid=IwAR2BJtpFqEllUEvyfZqSFLPae4iXccuyEjK8wzqjvaJucJPb1fPHNb8R508', 'collage_id' => '6'], 
        //     ['name' => 'واجبات الكترونية 1', 'path' => 'https://drive.google.com/drive/folders/1WN9K67EgUezAjdRNNvaVRHW0jL6n4D3t?fbclid=IwAR2BJtpFqEllUEvyfZqSFLPae4iXccuyEjK8wzqjvaJucJPb1fPHNb8R508', 'collage_id' => '6'], 
        //     ['name' => 'محاضرات مصورة', 'path' => 'https://drive.google.com/drive/folders/1iksOmWHQ9QHhTZJdth_KWGwS5s-D9RLm?usp=sharing', 'collage_id' => '6'],
        //     ['name' => 'امتحانات وجاهية', 'path' => 'https://drive.google.com/drive/folders/11eICSqRiXR7PG70jlxHgQMZ0nGVB2XBx?fbclid=IwAR2BJtpFqEllUEvyfZqSFLPae4iXccuyEjK8wzqjvaJucJPb1fPHNb8R508', 'collage_id' => '6'],
        //     ['name' => 'امتحانات الكترونية', 'path' => 'https://drive.google.com/drive/folders/1o0wT2QVBsbHig9qKDXJuu-5PcbAGlk6F?fbclid=IwAR2BJtpFqEllUEvyfZqSFLPae4iXccuyEjK8wzqjvaJucJPb1fPHNb8R508', 'collage_id' => '6'],
        //     //مختبر الكترونية
        //     ['name' => 'اسئلة سنوات', 'path' => 'https://drive.google.com/drive/folders/16KNyZ98XAtxoXVvqonlq-C1C3Fo9VM1w?fbclid=IwAR1DvrsmjDGYrsQCOv7fPeFRjQilXChA7j1kcSkOWznL3T_1HsVj0V4oaEk', 'collage_id' => '6'],
        //     //سنسور
        //     ['name' => 'فيرست سنسور', 'path' => 'https://drive.google.com/drive/u/0/folders/1nHNgPKr2qVKmOYWbY-jQxvtdaJS6aqEF', 'collage_id' => '6'],
        //     ['name' => 'سكند سنسور', 'path' => 'https://drive.google.com/drive/u/0/folders/1IDzC0cB0xkTasSzjsOrFlcD_Umq5feVO', 'collage_id' => '6'],
        //     ['name' => 'فاينل سنسور', 'path' => 'https://drive.google.com/drive/u/0/folders/1uyeM0dHXGfalatruTCrnMYFRcKvqUPcq', 'collage_id' => '6'],
        //     //بارشال
        //     ['name' => 'فيرست بارشال', 'path' => '', 'collage_id' => '6'],
        //     //بور 1
        //     ['name' => 'تلخيص فيرست', 'path' => 'https://drive.google.com/file/d/11qtYsK615CXQ06XAF9b0E_VONzp4P4Si/view', 'collage_id' => '6'],
        //     ['name' => 'تلخيص فاينل', 'path' => 'https://drive.google.com/file/d/18rkehodihRwiDgK3e5rrQFCUx1wc7VR1/view', 'collage_id' => '6'],
        //     ['name' => 'فيرست بور 1', 'path' => 'https://drive.google.com/drive/u/0/folders/1R06GFPxIR20dWhY2q_obnyXXDuGU4NkS', 'collage_id' => '6'],
        //     ['name' => 'سكند بور 1', 'path' => 'https://drive.google.com/drive/u/0/folders/1ryqhZ0WjQ6N9hL4jVtobqdVR9X6rgzMw', 'collage_id' => '6'],
        //     // بور 2
        //     ['name' => 'سكند بور 2', 'path' => 'https://drive.google.com/drive/u/0/folders/1Xhw6Xdg7sKcHoF6br_T1vTvAVptjPK8V', 'collage_id' => '6'],
        //     //مشين
        //     ['name' => 'كتاب مشين', 'path' => 'https://drive.google.com/drive/folders/18q7kiVfbqogYUv1ozwRLoQi5YIlMqXkG?fbclid=IwAR2Hz3lzCUhAixSkpOFMAiWqVIly1wtp5FQuMT61NV05tu7brrP28GsW8CY', 'collage_id' => '6'],
        //     ['name' => 'سلايدات مشين', 'path' => 'https://drive.google.com/drive/folders/122kCa27OueQqgMwpfN1QdWSRHTgn-NfJ?fbclid=IwAR2Hz3lzCUhAixSkpOFMAiWqVIly1wtp5FQuMT61NV05tu7brrP28GsW8CY', 'collage_id' => '6'],
        //     ['name' => 'واجبات مشين', 'path' => 'https://drive.google.com/drive/folders/1d1VdPa1UOfQsPVW6FZB9rOhnVzm__Mfm?fbclid=IwAR2Hz3lzCUhAixSkpOFMAiWqVIly1wtp5FQuMT61NV05tu7brrP28GsW8CY', 'collage_id' => '6'],
        //     ['name' => 'فيرست مشين', 'path' => 'https://drive.google.com/drive/folders/1usSHWZ-sVbL9cXRZCdk6utJ5qBBTJ43k', 'collage_id' => '6'],
        //     ['name' => 'سكند مشين', 'path' => 'https://drive.google.com/drive/folders/1eY-8onUKhm2yTXhGjeAkUkRbnT0BUFPU', 'collage_id' => '6'],
        //     ['name' => 'فاينل مشين', 'path' => 'https://drive.google.com/drive/folders/1JHikmECCBQ8rVTIUMmRjuKW6xN9fPOTA', 'collage_id' => '6'],
        // ];
        // DB::table('files')->insert($files);

        // $course_file_relation = [
        //     ['course_id' => '1', 'file_id' =>'1'],
        //     ['course_id' => '1', 'file_id' =>'2'],
        //     ['course_id' => '1', 'file_id' =>'3'],
        //     ['course_id' => '1', 'file_id' =>'4'],
        //     ['course_id' => '1', 'file_id' =>'5'],
        //     ['course_id' => '1', 'file_id' =>'6'],
        //     ['course_id' => '1', 'file_id' =>'7'],
        // ];
        // DB::table('course_files')->insert($course_file_relation);

        
    }
}